### ISSUE TITLE
Save username / password

### ISSUE THREAD

**Issue by jamespo** [jcherqui/rdcli#10]
A way to store the username & password in a config file would be great  - obviously if the password could be crypted that'd be even better.

**Comment by jcherqui** [comment]
Hello,

It's a good idea. This feature is now on `1.4.0` version.

You can set your real-debrid account as enviroment variable on your ~/.bashrc

```bash
export REALDEBRID_USERNAME=your_username
export REALDEBRID_PASSWORD=your_password
```

Encryption will be add later ;)

**Comment by jcherqui** [comment]
Hello @jamespo,

It's a good idea. This feature is now on `1.4.0` version.

You can set your real-debrid account as enviroment variable on your ~/.bashrc

```bash
export REALDEBRID_USERNAME=your_username
export REALDEBRID_PASSWORD=your_password
```

Encryption will be add later ;)
