### ISSUE TITLE
Error: Login error, VPN ?

### ISSUE THREAD

**Issue by jeremyj29** [jcherqui/rdcli#14]
Hi,

I try to use rdcli (version 1..3.2 et 1.3.3) and i always have an error : **Error: Login error, VPN ?**

I don't know what to do. I am not behind a VPN.

My OS is Archlinux which is on a dedicated server.

Regards,
Jérémy

**Comment by jcherqui** [comment]
Hello @jeremyj29,

Actually, real-debrid.com don't allow dedicated servers... You can try to ask them to allow your specific server on their website : https://real-debrid.com/support

I have no solutions to bypass this rule. Maybe soon !

**Comment by jeremyj29** [comment]
Ok !
Thanks for the answer.

Regards,
Jeremy
