### ISSUE TITLE
Error: RequestError: Error: Invalid URI "undefined/oauth/v2/token"

### ISSUE THREAD

**Issue by jamespo** [jcherqui/rdcli#6]
I'm getting this fatal error after login

**Comment by jcherqui** [comment]
@jamespo What is your version ?

**Comment by jamespo** [comment]
1.3.0

**Comment by jcherqui** [comment]
You can give logs and the link you have used please ? :)

**Comment by jamespo** [comment]
I think it must be related to the strange architecture I'm running it on (pine64 - aarch64). Seems fine on normal x64, so I'm closing.
